// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwPGJqlx4ejnpjmN0GYU1oLDZgavAxH6M',
    appId: '1:695462783641:web:e71a72f25fd12d8316e608',
    messagingSenderId: '695462783641',
    projectId: 'whatssapp2-78c9f',
    authDomain: 'whatssapp2-78c9f.firebaseapp.com',
    storageBucket: 'whatssapp2-78c9f.appspot.com',
    measurementId: 'G-LFMQL29166',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwQii-7e7qZ0YBVe00stYzR9rdXNuIbDE',
    appId: '1:695462783641:android:3af1ff4d9d0414f616e608',
    messagingSenderId: '695462783641',
    projectId: 'whatssapp2-78c9f',
    storageBucket: 'whatssapp2-78c9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAexpqGW7xiwRfqVXmPEp67mX3z2gH-gdg',
    appId: '1:695462783641:ios:95d2b3f3367e63d016e608',
    messagingSenderId: '695462783641',
    projectId: 'whatssapp2-78c9f',
    storageBucket: 'whatssapp2-78c9f.appspot.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAexpqGW7xiwRfqVXmPEp67mX3z2gH-gdg',
    appId: '1:695462783641:ios:8f50b5446dc3b9dd16e608',
    messagingSenderId: '695462783641',
    projectId: 'whatssapp2-78c9f',
    storageBucket: 'whatssapp2-78c9f.appspot.com',
    iosBundleId: 'com.example.whatsapp.RunnerTests',
  );
}
